#!/bin/bash

NAME=weird
DIR=/home/ali/facct-tutorial
USER=ali
GROUP=ali
WORKERS=1
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=/home/ali/miniforge3/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec poetry run gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-